name: K6 Load and Stress Test

on:
  push:
    branches:
      - main

jobs:
  load_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install k6
        run: |
          npm install -g k6

      - name: Run load test
        run: |
          k6 run load_test.js

  stress_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install k6
        run: |
          npm install -g k6

      - name: Run stress test
        run: |
          k6 run stress_test.js
