name: K6 Load Testing
on:
  push:
    branches:
      - main
jobs:
  load_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run local k6 test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: load_test.js
          #flags: --out json=Load_results.json
          
      - name: Upload performance test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report-load
          path: summary.html
          
  
