name: k6 Load Test

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install k6
        run: |
          curl -fsSL https://get.k6.io | sh

      - name: Run k6 load test
        run: k6 run test.js

